import type { Metadata, Viewport } from "next";
import '@fontsource/im-fell-double-pica-sc';
import '@fontsource/kaisei-decol';
// Supports weights 100-900
import '@fontsource-variable/montserrat';
import "./globals.css";
import { Toast } from "@/module/common/components/toast";
import { LayoutClient } from "./layoutClient";
import { createClient } from "@/supabase/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#D1B65E" },
    { media: "(prefers-color-scheme: light)", color: "#D1B65E" }
  ],
  colorScheme: "light"
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const client = await createClient()

  const user = await client.auth.getUser()

  return (
    <html lang="en">

      <body
        className="bg-base-100"
        data-theme="caramellatte"
      >
        <LayoutClient
          user={user.data.user}
        >
          <Toast />
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
